--DROP TABLE Course

CREATE TABLE Course(
CourseId INT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Teacher VARCHAR(100) NOT NULL
)

SELECT * FROM Course

INSERT INTO Course VALUES (10 ,'AERONAUTICAL ENGINEERING', 'DUSTIN' );

INSERT INTO Course VALUES (15 ,'BIOCHEMISTRY', 'BAIRO' );

INSERT INTO Course VALUES (20 ,'BIOTECHNOLOGY', 'SALTA' );

INSERT INTO Course VALUES (25 ,'PHYSICS', 'TINA' );

INSERT INTO Course VALUES (30 ,'MATHEMATICS', 'BASSIL' );

